# Power Management Configuration
# If there is no input for 5 minutes, it will enter idle mode.
CONFIG_ZMK_IDLE_TIMEOUT=300000
# Enabled deep sleep
CONFIG_ZMK_SLEEP=y
# After the idle state, if there is no input for an additional 30 minutes, it will enter deep sleep.
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=n
